#!/bin/bash

sum=0
numberCount=0
while read number
do
  if [ "$number" -eq "$number" ] 2>/dev/null; then
    ((numberCount = numberCount + 1))
    ((sum = sum + number))
  else
    echo "$number to nie liczba"
  fi
done

if [ "$numberCount" -ne "0" ];then
  echo -n "Średnia to "
  echo print $sum/$numberCount. | python
fi
